# Generated by Django 4.0.2 on 2022-03-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('email', models.CharField(max_length=70, verbose_name='E-mail')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('course', models.IntegerField(verbose_name='Course')),
                ('faculty', models.CharField(max_length=50, verbose_name='Faculty')),
            ],
        ),
    ]
