# Generated by Django 4.0.3 on 2022-03-24 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=50, verbose_name='Block name')),
                ('block_type', models.CharField(max_length=50, verbose_name='Block type')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(verbose_name='Floor number')),
                ('block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.block')),
            ],
            options={
                'ordering': ('floor_number',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=2, verbose_name='Gender')),
                ('course', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='Course')),
                ('faculty', models.CharField(choices=[('Faculty of Law and Social Sciences', 'Faculty of Law and Social Sciences'), ('Faculty of Education and Humanities Sciences', 'Faculty of Education and Humanities Sciences'), ('Faculty of Engineering and Natural Sciences', 'Faculty of Engineering and Natural Sciences'), ('Business school', 'Business school')], max_length=60, verbose_name='Faculty')),
                ('room', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Room')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(verbose_name='Room number')),
                ('faculty', models.CharField(choices=[('Faculty of Law and Social Sciences', 'Faculty of Law and Social Sciences'), ('Faculty of Education and Humanities Sciences', 'Faculty of Education and Humanities Sciences'), ('Faculty of Engineering and Natural Sciences', 'Faculty of Engineering and Natural Sciences'), ('Business school', 'Business school')], default='None', max_length=50, verbose_name='Faculty')),
                ('course', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='Course')),
                ('room_info', models.CharField(max_length=10, verbose_name='Type')),
                ('floor_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.floor')),
            ],
            options={
                'ordering': ('room_number',),
            },
        ),
    ]
