# Generated by Django 4.0.2 on 2022-03-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_form_delete_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last_name')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('course', models.CharField(max_length=50, verbose_name='Course')),
                ('faculty', models.CharField(max_length=50, verbose_name='Faculty')),
            ],
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
