# Generated by Django 4.0.3 on 2022-03-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_room_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='room',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Room'),
        ),
    ]
