# Generated by Django 4.0.2 on 2022-03-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_requests_course_alter_requests_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='course',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='Course'),
        ),
    ]
