# Generated by Django 4.0.2 on 2022-03-03 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_requests_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requests',
        ),
    ]
