# Generated by Django 4.0.3 on 2022-03-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('room_number',)},
        ),
    ]
