# Generated by Django 4.0.2 on 2022-03-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0006_delete_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=2, verbose_name='Gender')),
                ('course', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='Course')),
                ('faculty', models.CharField(choices=[('Faculty of Law and Social Sciences', 'Faculty of Law and Social Sciences'), ('Faculty of Education and Humanities Sciences', 'Faculty of Education and Humanities Sciences'), ('Faculty of Engineering and Natural Sciences', 'Faculty of Engineering and Natural Sciences'), ('Business school', 'Business school')], max_length=60, verbose_name='Faculty')),
            ],
        ),
    ]
