# Generated by Django 4.0.3 on 2022-03-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_entry_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='last_name',
        ),
        migrations.AddField(
            model_name='entry',
            name='type',
            field=models.CharField(choices=[('Log In', 'Log In'), ('Log Out', 'Log Out')], default='None', max_length=60, verbose_name='Type Of Entry'),
        ),
    ]
