# Generated by Django 4.0.3 on 2022-03-16 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_block_floor_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Req',
            new_name='User',
        ),
    ]
