# Generated by Django 4.0.3 on 2022-03-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_floor_options_alter_floor_floor_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_info',
            field=models.CharField(default='default title', max_length=10, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
